configs:
  params:
    server.insecure: true
controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: tokamak-optimism-monitoring
  resources:
    requests:
      cpu: 500m
      memory: 0.75Gi
repoServer:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: tokamak-optimism-monitoring
server:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: tokamak-optimism-monitoring
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
      alb.ingress.kubernetes.io/ssl-redirect: '443'
    tls:
      - hosts:
          - argocd.titan-goerli-nightly.tokamak.network
    hosts:
      - argocd.titan-goerli-nightly.tokamak.network
applicationSet:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: tokamak-optimism-monitoring
notifications:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: tokamak-optimism-monitoring
