# List of WS methods to whitelist.
ws_method_whitelist = [
  # List of ethereum standard APIs expects engine APIs. refer to https://ethereum.github.io/execution-apis/api-documentation
  "debug_getBadBlocks",
  "debug_getRawBlock",
  "debug_getRawHeader",
  "debug_getRawReceipts",
  "debug_getRawTransaction",

  "eth_accounts",
  "eth_blockNumber",
  "eth_call",
  "eth_chainId",
  "eth_coinbase",
  "eth_createAccessList",
  "eth_estimateGas",
  "eth_feeHistory",
  "eth_gasPrice",
  "eth_getBalance",
  "eth_getBlockByHash",
  "eth_getBlockByNumber",
  "eth_getBlockReceipts",
  "eth_getBlockTransactionCountByHash",
  "eth_getBlockTransactionCountByNumber",
  "eth_getCode",
  "eth_getFilterChanges",
  "eth_getFilterLogs",
  "eth_getLogs",
  "eth_getProof",
  "eth_getStorageAt",
  "eth_getTransactionByBlockHashAndIndex",
  "eth_getTransactionByBlockNumberAndIndex",
  "eth_getTransactionByHash",
  "eth_getTransactionCount",
  "eth_getTransactionReceipt",
  "eth_getUncleCountByBlockHash",
  "eth_getUncleCountByBlockNumber",
  "eth_maxPriorityFeePerGas",
  "eth_newBlockFilter",
  "eth_newFilter",
  "eth_newPendingTransactionFilter",
  "eth_sendRawTransaction",
  "eth_sendTransaction",
  "eth_sign",
  "eth_signTransaction",
  "eth_syncing",
  "eth_uninstallFilter",
]
ws_backend_group = "main"

[server]
rpc_host = "0.0.0.0"
rpc_port = 8080
ws_host = "0.0.0.0"
ws_port = 8085
max_body_size_bytes = 10485760
max_concurrent_rpcs = 10000
log_level = "info"
enable_pprof = true

[redis]
url = "redis://redis-svc.redis:6379/0"

[cache]
enabled = true

[metrics]
enabled = true
host = "0.0.0.0"
port = 9761

[backend]
response_timeout_seconds = 5
max_response_size_bytes = 104857600
max_retries = 3
out_of_service_seconds = 20


[backends]
[backends.alchemy]
rpc_url = "https://eth-sepolia.g.alchemy.com/v2/x4EOshikyKeyJci-23VSqFnwKIddeS7f"
ws_url = "wss://eth-sepolia.g.alchemy.com/v2/x4EOshikyKeyJci-23VSqFnwKIddeS7f"
max_rps = 1000
max_ws_conns = 0
consensus_receipts_target = "alchemy_getTransactionReceipts"
strip_trailing_xff = true

[backends.infura_steven1]
rpc_url = "https://sepolia.infura.io/v3/98934cc6fa14459f8e5ee0cdfe1eed0a"
ws_url = "wss://sepolia.infura.io/ws/v3/98934cc6fa14459f8e5ee0cdfe1eed0a"
max_rps = 1000
max_ws_conns = 0
consensus_receipts_target = "eth_getBlockReceipts"
strip_trailing_xff = true

[backends.infura_steven2]
rpc_url = "https://sepolia.infura.io/v3/274dc9c47885483ca708968ee0e75d06"
ws_url = "wss://sepolia.infura.io/ws/v3/274dc9c47885483ca708968ee0e75d06"
max_rps = 1000
max_ws_conns = 0
consensus_receipts_target = "eth_getBlockReceipts"
strip_trailing_xff = true

[backends.infura_theo1]
rpc_url = "https://sepolia.infura.io/v3/053e5d95616744d4b30a80fb885bacb8"
ws_url = "wss://sepolia.infura.io/ws/v3/053e5d95616744d4b30a80fb885bacb8"
max_rps = 1000
max_ws_conns = 0
consensus_receipts_target = "eth_getBlockReceipts"
strip_trailing_xff = true

[backends.infura_theo2]
rpc_url = "https://sepolia.infura.io/v3/adbdb3ac93674147934afa48bdccacef"
ws_url = "wss://sepolia.infura.io/ws/v3/adbdb3ac93674147934afa48bdccacef"
max_rps = 1000
max_ws_conns = 0
consensus_receipts_target = "eth_getBlockReceipts"
strip_trailing_xff = true

[backend_groups]
[backend_groups.main]
backends = [
  "alchemy",
  "infura_steven1",
  "infura_steven2",
  "infura_theo1",
  "infura_theo2",
]

[backend_groups.alchemy]
backends = ["alchemy"]
# Enable consensus awareness for backend group, making it act as a load balancer, default false
# consensus_aware = true
# Period in which the backend wont serve requests if banned, default 5m
# consensus_ban_period = "1m"
# Maximum delay for update the backend, default 30s
# consensus_max_update_threshold = "20s"
# Maximum block lag, default 8
# consensus_max_block_lag = 16
# Minimum peer count, default 3
# consensus_min_peer_count = 4

[rpc_method_mappings]
# List of ethereum standard APIs expects engine APIs. refer to https://ethereum.github.io/execution-apis/api-documentation
debug_getBadBlocks = "main"
debug_getRawBlock = "main"
debug_getRawHeader = "main"
debug_getRawReceipts = "main"
debug_getRawTransaction = "main"
eth_accounts = "main"
eth_blockNumber = "main"
eth_call = "main"
eth_chainId = "main"
eth_coinbase = "main"
eth_createAccessList = "main"
eth_estimateGas = "main"
eth_feeHistory = "main"
eth_gasPrice = "main"
eth_getBalance = "main"
eth_getBlockByHash = "main"
eth_getBlockByNumber = "main"
eth_getBlockReceipts = "main"
eth_getBlockTransactionCountByHash = "main"
eth_getBlockTransactionCountByNumber = "main"
eth_getCode = "main"
eth_getFilterChanges = "main"
eth_getFilterLogs = "main"
eth_getLogs = "main"
eth_getProof = "main"
eth_getStorageAt = "main"
eth_getTransactionByBlockHashAndIndex = "main"
eth_getTransactionByBlockNumberAndIndex = "main"
eth_getTransactionByHash = "main"
eth_getTransactionCount = "main"
eth_getTransactionReceipt = "main"
eth_getUncleCountByBlockHash = "main"
eth_getUncleCountByBlockNumber = "main"
eth_maxPriorityFeePerGas = "main"
eth_newBlockFilter = "main"
eth_newFilter = "main"
eth_newPendingTransactionFilter = "main"
eth_sendRawTransaction = "main"
eth_sendTransaction = "main"
eth_sign = "main"
eth_signTransaction = "main"
eth_syncing = "main"
eth_uninstallFilter = "main"

alchemy_getTransactionReceipts = "alchemy"
