apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgresql

generatorOptions:
  disableNameSuffixHash: true

resources:
- ../../bases
- namespace.yaml

configMapGenerator:
- literals:
  - APP_NAME=postgresql
  - ENV_NAME=local
  name: postgresql-config
