apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: redis

generatorOptions:
  disableNameSuffixHash: true

resources:
  - namespace.yaml
  - ../../bases

patches:
  - path: resource_override.yaml

configMapGenerator:
  - literals:
      - APP_NAME=redis
      - ENV_NAME=aws
    name: redis-config
