apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  template:
    spec:
      containers:
      - name: redis
        command: ['redis-server', '/redis-conf/redis.conf']
        resources:
          requests:
            cpu: 0.5
            memory: 0.75Gi
          limits:
            cpu: 0.5
            memory: 0.75Gi
        volumeMounts:
        - mountPath: /redis-conf
          name: redis-volume-config
      volumes:
      - name: redis-volume-config
        configMap:
          name: redis-service-config
          items:
          - key: redis-config-params
            path: redis.conf
