---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxyd-l2geth
spec:
  replicas: 1
  template:
    spec:
      terminationGracePeriodSeconds: 10
      restartPolicy: Always
      initContainers:
        - name: wait-for-redis
          image: busybox:latest
          command: ['sh', '-c', 'until nc -vz redis-svc.redis 6379; do echo "Waiting for redis..."; sleep 1; done;']
      containers:
        - name: proxyd-l2geth
          image: onthertech/titan-proxyd
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8085
              protocol: TCP
            - containerPort: 9761
              protocol: TCP
          command: ['bin/proxyd', '/config/proxyd-l2geth-config.toml']
          resources: {}
          volumeMounts:
            - name: config-files
              mountPath: /config

      volumes:
        - name: config-files
          configMap:
            name: proxyd-l2geth-config-files
            defaultMode: 0777
