---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxyd-l2geth
spec:
  selector:
    matchLabels:
      app: proxyd-l2geth
  replicas: 1
  template:
    spec:
      terminationGracePeriodSeconds: 10
      restartPolicy: Always
      initContainers:
        - name: wait-for-redis
          image: busybox:latest
          command:
            [
              "sh",
              "-c",
              'until nc -vz redis-svc.redis 6379; do echo "Waiting for redis..."; sleep 1; done;',
            ]
      containers:
        - name: proxyd
          image: tokamaknetwork/thanos-proxyd
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8085
              protocol: TCP
            - containerPort: 9761
              protocol: TCP
          command: ["bin/proxyd", "/config/proxyd-l2geth-config.toml"]
          resources: {}
          volumeMounts:
            - name: proxyd-config
              mountPath: /config

      volumes:
        - name: proxyd-config
          configMap:
            name: proxyd-l2geth
            defaultMode: 0777
