apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: graph-node

generatorOptions:
  disableNameSuffixHash: true

resources:
- namespace.yaml
- ingress.yaml
- pv.yaml
- pvc.yaml
- ../../../envs/titan-sepolia-test
- ../../../bases/ipfs
- ../../../bases/graph-node

patchesStrategicMerge:
- resource_override.yaml
