ws_method_whitelist = [
  "eth_subscribe",
  "eth_call",
  "eth_chainId",
  "net_version"
]
ws_backend_group = "main"

[server]
rpc_host = "0.0.0.0"
rpc_port = 8080
ws_host = "0.0.0.0"
ws_port = 8085
max_body_size_bytes = 10485760
max_concurrent_rpcs = 1000

[redis]
url = "redis://redis-svc.redis:6379"

[metrics]
enabled = true
host = "0.0.0.0"
port = 9761

[backend]
response_timeout_seconds = 3
max_response_size_bytes = 5242880
max_retries = 1
out_of_service_seconds = 5

[backends]
[backends.hardhat]
rpc_url = "https://hardhat.rpc.tokamak.network"
ws_url = "https://hardhat.rpc.tokamak.network/ws"
max_rps = 10
max_ws_conns = 0

[backend_groups]
[backend_groups.main]
backends = ["hardhat"]

[rpc_method_mappings]
eth_call = "main"
eth_chainId = "main"
eth_blockNumber = "main"
net_version = "main"
eth_syncing = "main"

[rate_limit]
enable_backend_rate_limiter = false
