# Origin: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml

nodeExporter:
  enabled: false

prometheus:
  prometheusSpec:
    retentionSize: 1GB
    additionalScrapeConfigs:
      - job_name: data-transport-layer
        static_configs:
          - targets:
              - data-transport-layer-svc.default:7878
      - job_name: batch-submitter
        static_configs:
          - targets:
              - batch-submitter-svc.default:7300
      - job_name: l2geth
        metrics_path: /debug/metrics/prometheus
        static_configs:
          - targets:
              - l2geth-svc.default:6060
      - job_name: l2geth-replica
        metrics_path: /debug/metrics/prometheus
        static_configs:
        - targets:
            - l2geth-replica-svc.default:6060
      - job_name: proxyd
        static_configs:
          - targets:
              - proxyd-svc.default:9761
      - job_name: l1geth
        metrics_path: /debug/metrics/prometheus
        static_configs:
          - targets:
              - goerli.rpc.tokamak.network:6060
      - job_name: relayer
        static_configs:
          - targets:
              - relayer-svc.default:7300
      - job_name: blackbox
        metrics_path: /probe
        params:
          module: [http_2xx]
        static_configs:
          - targets:
            - http://app-gateway-svc.app-gateway
            - http://blockscout-svc.app-blockscout
        relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: target
        - target_label: __address__
          replacement: blackbox-exporter-prometheus-blackbox-exporter.monitoring:9115
      - job_name: blackbox-eth-node-synced
        metrics_path: /probe
        params:
          module: [http_post_eth_node_synced_2xx]
        static_configs:
          - targets:
            - https://goerli.rpc.tokamak.network
        relabel_configs:
        - source_labels: [module]
          target_label: __param_module
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: target
        - target_label: __address__
          replacement: blackbox-exporter-prometheus-blackbox-exporter.monitoring:9115
      - job_name: blackbox-eth-block-number
        metrics_path: /probe
        params:
          module: [http_post_eth_block_number_2xx]
        static_configs:
          - targets:
            - http://proxyd-svc.default:8545
            - https://goerli.rpc.tokamak.network
        relabel_configs:
        - source_labels: [module]
          target_label: __param_module
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: target
        - target_label: __address__
          replacement: blackbox-exporter-prometheus-blackbox-exporter.monitoring:9115
      - job_name: tcp-health-check
        metrics_path: /probe
        params:
          module: [tcp_connect]
        static_configs:
          - targets:
            - redis-svc.redis:6379
        relabel_configs:
        - source_labels: [module]
          target_label: __param_module
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: target
        - target_label: __address__
          replacement: blackbox-exporter-prometheus-blackbox-exporter.monitoring:9115
grafana:
  adminPassword: admin
