---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  template:
    spec:
      terminationGracePeriodSeconds: 10
      restartPolicy: Always
      containers:
        - name: gateway
          image: onthertech/tokamak.gateway
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: gateway-volume
              readOnly: true
              mountPath: /usr/share/caddy/config
      volumes:
        - name: gateway-volume
          configMap:
            name: gateway-config
