apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-notif
generatorOptions:
  disableNameSuffixHash: true

resources:
  - namespace.yaml
  - ../../../bases
  - ../../../envs/goerli

patchesStrategicMerge:
  - resource_override.yaml
