---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  replicas: 1
  serviceName: redis-svc
  template:
    spec:
      terminationGracePeriodSeconds: 10
      restartPolicy: Always
      containers:
        - name: redis
          image: redis:alpine
          command: ['redis-server']
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
              protocol: TCP
          resources: {}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: redis-volume
              mountPath: /data
              subPath: redis
      volumes:
        - name: redis-volume
          persistentVolumeClaim:
            claimName: redis-pvc
