apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: redis

generatorOptions:
  disableNameSuffixHash: true

resources:
- ../../bases
- namespace.yaml

patchesStrategicMerge:
- resource_override.yaml

configMapGenerator:
- literals:
  - APP_NAME=redis
  - ENV_NAME=local
  name: redis-config
