apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: redis

generatorOptions:
  disableNameSuffixHash: true

resources:
- namespace.yaml
- ../../bases


patchesStrategicMerge:
- resource_override.yaml

configMapGenerator:
  - name: redis-config
    literals:
      - APP_NAME=redis
      - ENV_NAME=local