---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  template:
    spec:
      containers:
      - name: redis
        resources:
          requests:
            cpu: 0.5
            memory: 1.5Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-service-config
data:
  redis-config-params: |
    maxmemory 1024mb
    maxmemory-policy allkeys-lru 