---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visualizer
spec:
  replicas: 1
  template:
    spec:
      terminationGracePeriodSeconds: 10
      restartPolicy: Always
      containers:
        - name: visualizer
          image: ghcr.io/blockscout/visualizer
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8050
              protocol: TCP
          envFrom:
            - configMapRef:
                name: visualizer
