---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-contract-verifier
spec:
  replicas: 1
  template:
    spec:
      terminationGracePeriodSeconds: 10
      restartPolicy: Always
      containers:
        - name: smart-contract-verifier
          image: ghcr.io/blockscout/smart-contract-verifier:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8050
              protocol: TCP
          envFrom:
            - configMapRef:
                name: smart-contract-verifier
