apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: data-transport-layer
    envs:
      - ./data-transport-layer.env
  - name: l2geth
    envs:
      - ./l2geth.env
  - name: batch-submitter
    envs:
      - ./batch-submitter.env
  - name: relayer
    envs:
      - ./relayer.env
  - name: common
    envs:
      - ./common.env
  - name: config-files
    files:
      - ./proxyd-config.toml
  - name: l2geth-replica
    envs:
      - ./l2geth-replica.env
