apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: titan-batcher-config
    envs:
      - ./titan-batcher.env
  - name: titan-proposer-config
    envs:
      - ./titan-proposer.env

secretGenerator:
  - name: secret
    envs:
      - ./secret.env