---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-notif
spec:
  template:
    spec:
      containers:
        - name: app-notif
          resources:
            limits:
              cpu: 0.5
              memory: 0.75Gi
          envFrom:
            - configMapRef:
                name: notif-app-config
