---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: op-geth-pv
  labels:
    app: op-geth
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-043b6b382b4e176e6
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: op-challenger-pv
  labels:
    app: op-challenger
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-043b6b382b4e176e6
