---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: op-geth-pvc
spec:
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  selector:
    matchLabels:
      app: op-geth
