---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tx-batch-submitter
spec:
  replicas: 1
  template:
    spec:
      terminationGracePeriodSeconds: 10
      restartPolicy: Always
      initContainers:
        - name: wait-for-l1
          image: nicolaka/netshoot
          command: ['bash', '-c', '/script/wait/wait-for-l1.sh']
          volumeMounts:
            - name: wait-scripts
              mountPath: /script/wait
          envFrom:
            - configMapRef:
                name: common
        - name: wait-for-deployer
          image: nicolaka/netshoot
          command: ['bash', '-c', '/script/wait/wait-for-deployer.sh']
          envFrom:
            - configMapRef:
                name: common
          volumeMounts:
            - name: wait-scripts
              mountPath: /script/wait
        - name: wait-for-l2
          image: nicolaka/netshoot
          command: ['bash', '-c', '/script/wait/wait-for-l2.sh']
          envFrom:
            - configMapRef:
                name: common
          volumeMounts:
            - name: wait-scripts
              mountPath: /script/wait
      containers:
        - name: tx-batch-submitter
          image: tokamaknetwork/titan-batch-submitter
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7300
              protocol: TCP
          command: ['./batch-submitter.sh']
          resources: {}
          envFrom:
            - configMapRef:
                name: tx-batch-submitter
            - secretRef:
                name: secret
      volumes:
        - name: wait-scripts
          configMap:
            name: wait-scripts
            defaultMode: 0777
