---
apiVersion: v1
kind: Service
metadata:
  name: tx-batch-submitter-svc
spec:
  ports:
    - name: http
      port: 7300
      protocol: TCP
      targetPort: 7300
  selector:
    app: tx-batch-submitter
