apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: aws-configmap
    namespace: kube-system
    envs:
      - ./aws.env
