resources:
  limits:
    cpu: 0.5
    memory: 0.75Gi
  requests:
    cpu: 0.5
    memory: 0.75Gi

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://amp-prometheus-chart-server.prometheus.svc.cluster.local
        access: proxy
        isDefault: true

sidecar:
  dashboards:
    enabled: true
    searchNamespace: "ALL"
  provider:
    allowUiUpdates: true
