profile         = "dev" # you must change it in your local file ~/.aws/config
region          = "ap-northeast-2"
azs             = ["ap-northeast-2a", "ap-northeast-2b"]
network_name    = "goerli-nightly"
cluster_name    = "dev-titan-goerli-nightly"
cluster_version = 1.27
vpc_cidr        = "192.168.0.0/16"
vpc_name        = "dev-titan-goerli-nightly/VPC"
efs_name        = "dev-titan-goerli-nightly"
parent_domain   = "dev.titan-goerli-nightly.tokamak.network"
service_names   = ["argocd", "rpc", "explorer", "thegraph", "ipfs", "grafana", "kibana", "gateway"]
