apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
spec:
  project: default
  sources:
    # kube-prometheus-stack
    - repoURL: 'https://prometheus-community.github.io/helm-charts'
      chart: kube-prometheus-stack
      targetRevision: '58.6.0'
      helm:
        valueFiles:
          - $repo/monitoring/metrics/override_values/aws/thanos-sepolia-test/config.yaml
          - $repo/monitoring/metrics/override_values/aws/thanos-sepolia-test/prometheus.yaml
          - $repo/monitoring/metrics/override_values/aws/thanos-sepolia-test/grafana.yaml
          - $repo/monitoring/metrics/override_values/aws/thanos-sepolia-test/alert-manager.yaml
          - $repo/monitoring/metrics/override_values/aws/thanos-sepolia-test/alerts/alerts-op-node.yaml
          - $repo/monitoring/metrics/override_values/aws/thanos-sepolia-test/alerts/alerts-op-batcher.yaml
          - $repo/monitoring/metrics/override_values/aws/thanos-sepolia-test/alerts/alerts-op-proposer.yaml
    # prometheus-blackbox-exporter
    - repoURL: 'https://prometheus-community.github.io/helm-charts'
      chart: prometheus-blackbox-exporter
      targetRevision: '8.17.0'
      helm:
        valueFiles:
          - $repo/monitoring/metrics/override_values/aws/thanos-sepolia-test/blackbox.yaml
    # grafana dashboards
    # - repoURL: 'https://github.com/tokamak-network/tokamak-infra.git'
    #   path: monitoring/metrics/dashboards
    #   targetRevision: main
    # repository to override
    - repoURL: 'https://github.com/tokamak-network/tokamak-infra.git'
      # targetRevision: main
      targetRevision: OR-1573-configure-alert-thanos-sepolia-test
      ref: repo

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true