apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thanos

spec:
  project: default
  source:
    repoURL: 'https://github.com/tokamak-network/tokamak-titan-infra.git'
    path: thanos/kustomize/overlays/thanos-sepolia-test
    targetRevision: OR-1382-Prepare-new-network-deploy
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
