---
apiVersion: v1
kind: Service
metadata:
  name: data-transport-layer-svc
spec:
  selector:
    app: data-transport-layer
  type: LoadBalancer
  ports:
    - name: http
      port: 7878
      targetPort: 7878
