---
# Source: kibana/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: elastic-stack
  labels: 
    app: kibana
data:
  kibana.yml: |
    elasticsearch.hosts: http://elasticsearch:9200
    elasticsearch.username: kibana_system
    elasticsearch.password: tokamak!@#