apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: titan2

spec:
  project: default
  source:
    repoURL: 'https://github.com/tokamak-network/tokamak-titan-infra.git'
    path: titan2/kustomize/overlays/titan-sepolia-test
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
