---
apiVersion: v1
kind: Service
metadata:
  name: l2geth-svc
spec:
  selector:
    app: l2geth
  type: LoadBalancer
  ports:
    - name: rpc
      port: 8545
      targetPort: 8545
    - name: websocket
      port: 8546
      targetPort: 8546
