apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/tokamak-network/tokamak-titan-infra'
    path: ops/argocd/override_values/thanos-sepolia-test/applications
    targetRevision: OR-1382-Prepare-new-network-deploy
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
