---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: op-geth-pv
  labels:
    app: op-geth
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0f1155dbf0b9fed4f
