apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: thegraph

generatorOptions:
  disableNameSuffixHash: true

resources:
- namespace.yaml
- ingress.yaml
- ../../../envs/goerli-nightly
- ../../../bases/ipfs
- ../../../bases/graph-node

patchesStrategicMerge:
- resource_override.yaml
- service_override.yaml

configMapGenerator:
- literals:
  - APP_NAME=thegraph
  - CLUSTER_NAME=goerli-nightly
  - ENV_NAME=aws
  name: thegraph-config
images:
- name: ipfs/go-ipfs
  newTag: v0.10.0
- name: graphprotocol/graph-node
  newTag: v0.31.0
