---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ipfs-pv
  labels:
    app: ipfs
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0c1c971912fd33e4b
