---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-notif
spec:
  replicas: 1
  template:
    spec:
      terminationGracePeriodSeconds: 10
      restartPolicy: Always
      containers:
        - name: app-notif
          image: onthertech/titan-events-listener:nightly
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: notif-app-config
          resources:
            limits:
              cpu: 0.5
              memory: 0.75Gi
