---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-notif
spec:
  replicas: 1
  template:
    spec:
      terminationGracePeriodSeconds: 10
      restartPolicy: Always
      containers:
        - name: app-notif
          image: onthertech/titan-events-listener:nightly
          imagePullPolicy: Always
---

