---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-notif
spec:
  replicas: 1
  template:
    spec:
      terminationGracePeriodSeconds: 10
      restartPolicy: Always
      containers:
        - name: app-notif
          image: notif-image
          imagePullPolicy: IfNotPresent
          env:
            - name: L1_URL
              valueFrom:
                configMapKeyRef:
                  name: app-notif-config
                  key: l1-ws-url
            - name: L2_URL
              valueFrom:
                configMapKeyRef:
                  name: app-notif-config
                  key: l2-ws-url
            - name: SLACK_URL
              valueFrom:
                configMapKeyRef:
                  name: app-notif-config
                  key: slack-url
            - name: L1_STANDARD_BRIDGE
              valueFrom:
                configMapKeyRef:
                  name: app-notif-config
                  key: l1-standard-bridge
            - name: L2_STANDARD_BRIDGE
              valueFrom:
                configMapKeyRef:
                  name: app-notif-config
                  key: l2-standard-bridge
            - name: PLATFORM
              valueFrom:
                configMapKeyRef:
                  name: app-notif-config
                  key: platform
          resources:
            limits:
              cpu: 0.5
              memory: 0.75Gi
