apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


generatorOptions:
  disableNameSuffixHash: true

resources:
- ../../../bases/data-transport-layer
- ../../../bases/l2geth
- ../../../bases/batch-submitter
- ../../../bases/relayer
- ../../../bases/roles
- ingress.yaml
- sc.yaml
- pv.yaml
- pvc.yaml
- ../../../envs/goerli-nightly
- ../../../scripts

patchesStrategicMerge:
- resource_override.yaml
- service_override.yaml

configMapGenerator:
- literals:
  - CLUSTER_NAME=goerli-nightly
  - ENV_NAME=aws
  name: chain-config
images:
- name: onthertech/optimism.batch-submitter-service
  newTag: nightly-0.1.12
- name: onthertech/optimism.data-transport-layer
  newTag: nightly-0.5.47
- name: onthertech/optimism.l2geth
  newTag: nightly-0.5.24
- name: onthertech/optimism.tokamak-message-relayer
  newTag: nightly-0.5.5

