---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: l2geth-pv
  labels:
    app: l2geth
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-08b35f2bb5ab229d9
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-transport-layer-pv
  labels:
    app: data-transport-layer
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-08b35f2bb5ab229d9
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: l2geth-replica-pv
  labels:
    app: l2geth-replica
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-08b35f2bb5ab229d9
