---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: l2geth-pvc
spec:
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  selector:
    matchLabels:
      app: l2geth
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-transport-layer-pvc
spec:
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  selector:
    matchLabels:
      app: data-transport-layer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: l2geth-replica-pvc
spec:
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  selector:
    matchLabels:
      app: l2geth-replica
