apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: thanos-app-notif
generatorOptions:
  disableNameSuffixHash: true

resources:
- namespace.yml
- ../../../bases
- ../../../envs/sepolia-nightly

patches:
- path: resource_override.yml
images:
- name:
  newTag:
