apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blockscout
spec:
  project: default
  sources:
    # blockscout-stack
    - repoURL: 'https://blockscout.github.io/helm-charts'
      chart: blockscout-stack
      targetRevision: '*-0'
      helm:
        valueFiles:
          - $repo/apps/blockscout-stack/override_values/titan-sepolia-test/blockscout.yaml
          - $repo/apps/blockscout-stack/override_values/titan-sepolia-test/config.yaml
          - $repo/apps/blockscout-stack/override_values/titan-sepolia-test/frontend.yaml
          - $repo/apps/blockscout-stack/override_values/titan-sepolia-test/stats.yaml
    # repoURL
    - repoURL: 'https://github.com/tokamak-network/tokamak-infra.git'
      targetRevision: main
      ref: repo

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: blockscout
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
