apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

generatorOptions:
  disableNameSuffixHash: true

resources:
  - blockscout.yaml
  - graph-node.yaml
  - redis.yaml
  - titan2.yaml
