{
 "title": "app-notif-metris",
 "time": { "from": "2023-10-29T18:05:14.000Z", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Deposit-Withdrawal amount (Ether)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "event_listener_deposited_finalized_amount{symbol=\"ETH\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "event_listener_withdrawal_finalized_amount{symbol=\"Ether\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deposit-Withdrawal amount (TON)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "event_listener_deposited_finalized_amount{symbol=\"TON\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "event_listener_withdrawal_finalized_amount{symbol=\"TON\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deposit Amount (Ether)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "event_listener_deposited_finalized_amount{symbol=\"ETH\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Withdrawal Amount (Ether)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "event_listener_withdrawal_finalized_amount{symbol=\"Ether\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deposit Amount (TON)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "event_listener_deposited_finalized_amount{symbol=\"TON\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Withdrawal Amount (TON)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "event_listener_withdrawal_finalized_amount{symbol=\"TON\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Num of Deposit Tx (Ether)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "event_listener_count_deposit_finalized{symbol=\"ETH\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Num of Withdrawal Tx (Ether)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "event_listener_count_withdrawal_finalized{symbol=\"Ether\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Num of Deposit Tx (TON)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "event_listener_count_deposit_finalized{symbol=\"TON\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Num of Withdrawal Tx (TON)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "event_listener_count_withdrawal_finalized{symbol=\"TON\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Num of Deposit-Withdrawal Tx",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 14, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(event_listener_count_deposit_finalized)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(event_listener_count_withdrawal_finalized)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Num of Deposit Tx",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 14, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(event_listener_count_deposit_finalized)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Num of Withdrawal Tx",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 14, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(event_listener_count_withdrawal_finalized)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}