{
 "title": "Application DashBoard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Healthy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "L1 Geth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"l1geth\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "L2 Geth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"l2geth\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "L2 Geth Replica",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"l2geth-replica\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batch Submitter",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"batch-submitter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data Transport Layer",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"data-transport-layer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Relayer",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"relayer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{target=~\"http://app-gateway-svc.app-gateway\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Explorer",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{target=~\"http://blockscout-svc.app-blockscout\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Postgresql",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{target=\"postgresql-svc.postgresql:5432\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{target=\"redis-svc.redis:6379\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "L2 Geth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Block",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_head_block{job=~\"l2geth\"}"
    }
   ]
  },
  {
   "title": "Chain head",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "chain_head_receipt{job=~\"l2geth\"}",
     "legendFormat": "transaction"
    },
    {
     "expr": "chain_head_block{job=~\"l2geth\"}",
     "legendFormat": "block"
    }
   ]
  },
  {
   "title": "Transaction",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_head_receipt{job=~\"l2geth\"}"
    }
   ]
  },
  { "title": "Batch Submitter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Sequencer Balance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "batch_submitter_sequencer_balance_eth{job=\"batch-submitter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batch Submissions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 17 },
   "targets": [
    {
     "expr": "batch_submitter_sequencer_batches_submitted{job=\"batch-submitter\"}",
     "legendFormat": "sequencer"
    },
    {
     "expr": "batch_submitter_proposer_batches_submitted{job=\"batch-submitter\"}",
     "legendFormat": "proposer"
    }
   ]
  },
  {
   "title": "Batch Failed Submissions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 17 },
   "targets": [
    {
     "expr": "batch_submitter_sequencer_failed_submissions{job=\"batch-submitter\"}",
     "legendFormat": "sequencer"
    },
    {
     "expr": "batch_submitter_proposer_failed_submissions{job=\"batch-submitter\"}",
     "legendFormat": "proposer"
    }
   ]
  },
  {
   "title": "Proposer Balance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "batch_submitter_proposer_balance_eth{job=\"batch-submitter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Data Transport Layer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "L1 BlockNumber",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_head_block{job=~\"l1geth\"}"
    }
   ]
  },
  {
   "title": "Main Service Failures",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 24 },
   "targets": [
    {
     "expr": "data_transport_layer_main_service_failures{job=\"data-transport-layer\"}",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Synced Blocks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "data_transport_layer_highest_synced_l1_block{job=\"data-transport-layer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "No Synced Blocks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "data_transport_layer_highest_synced_l1_block{job=\"data-transport-layer\"}"
    },
    {
     "expr": "chain_head_block{job=~\"l1geth\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Synced Blocks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "data_transport_layer_highest_synced_l1_block{job=\"data-transport-layer\"}",
     "legendFormat": "Synced Blocks"
    },
    {
     "expr": "chain_head_receipt{job=~\"l1geth\"}",
     "legendFormat": "L1 Blocks"
    }
   ]
  },
  {
   "title": "No Synced Blocks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "data_transport_layer_highest_synced_l1_block{job=\"data-transport-layer\"}",
     "legendFormat": "Synced Blocks"
    },
    {
     "expr": "chain_head_receipt{job=~\"l1geth\"}",
     "legendFormat": "L1 Blocks"
    }
   ]
  },
  { "title": "Relayer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Known L2 BlockNumber",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "message_relayer_highest_known_l2_tx{job=\"relayer\"}"
    }
   ]
  },
  {
   "title": "Unhandled Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 37 },
   "targets": [
    {
     "expr": "message_relayer_unhandled_errors{job=\"relayer\"}",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Checked L2 BlockNumber",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "message_relayer_highest_checked_l2_tx{job=\"relayer\"} - 1"
    }
   ]
  },
  {
   "title": "No Checked Blocks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "message_relayer_highest_known_l2_tx{job=\"relayer\"}"
    },
    {
     "expr": "message_relayer_highest_checked_l2_tx{job=\"relayer\"} - 1 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Checked Blocks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(message_relayer_highest_checked_l2_tx{job=\"relayer\"} - 1 < bool 0 and message_relayer_highest_checked_l2_tx{job=\"relayer\"}) + message_relayer_highest_checked_l2_tx{job=\"relayer\"} - 1",
     "legendFormat": "Checked Blocks"
    },
    {
     "expr": "message_relayer_highest_known_l2_tx{job=\"relayer\"}",
     "legendFormat": "L2 Blocks"
    }
   ]
  },
  {
   "title": "No Checked Blocks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(message_relayer_highest_checked_l2_tx{job=\"relayer\"} - 1 < bool 0 and message_relayer_highest_checked_l2_tx{job=\"relayer\"}) + message_relayer_highest_checked_l2_tx{job=\"relayer\"} - 1",
     "legendFormat": "Synced Blocks"
    },
    {
     "expr": "message_relayer_highest_known_l2_tx{job=\"relayer\"}",
     "legendFormat": "L1 Blocks"
    }
   ]
  }
 ]
}