{
 "title": "Proxyd Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Proxyd Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Proxyd RPC Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (increase(proxyd_rpc_requests_total{job=\"proxyd\"}[$__range])) + sum by (job) (increase(proxyd_cache_hits_total[$__range]))"
    }
   ]
  },
  {
   "title": "Proxyd RPC Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (job) (increase(proxyd_rpc_requests_total{job=\"proxyd\"}[1m])) + sum by (job) (increase(proxyd_cache_hits_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proxyd RPC Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (backend_name) (increase(proxyd_rpc_errors_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proxyd RPC Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (backend_name) (increase(proxyd_rpc_errors_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend HTTP Response",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (backend_name,status_code) (increase(proxyd_rpc_backend_http_response_codes_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend HTTP Response",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 9 },
   "targets": [
    {
     "expr": "sum by (backend_name,status_code) (increase(proxyd_rpc_backend_http_response_codes_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Response",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 9 },
   "targets": [
    {
     "expr": "sum by (method) (increase(proxyd_cache_hits_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Response",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (method) (increase(proxyd_cache_hits_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proxyd RPC Latency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(proxyd_http_request_duration_seconds_sum[$__range])/increase(proxyd_http_request_duration_seconds_count[$__range])"
    }
   ]
  },
  {
   "title": "Proxyd RPC Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(proxyd_http_request_duration_seconds_sum[1m])/rate(proxyd_http_request_duration_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}