---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockscout
spec:
  replicas: 1
  template:
    spec:
      terminationGracePeriodSeconds: 10
      restartPolicy: Always
      containers:
        - name: blockscout
          image: 005310045109.dkr.ecr.ap-northeast-2.amazonaws.com/tokamak-optimism-blockscout
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
              protocol: TCP
          command: ['/bin/sh','-c']
          args: ['bin/blockscout eval "Elixir.Explorer.ReleaseTasks.create_and_migrate()" && bin/blockscout start']
          envFrom:
            - configMapRef:
                name: blockscout
            - secretRef:
                name: secret
