---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-blockscout
spec:
  replicas: 1
  template:
    spec:
      terminationGracePeriodSeconds: 10
      restartPolicy: Always
      initContainers:
        - name: wait-for-database
          image: busybox:latest
          command: ['sh', '-c', 'until nc -vz postgresql-svc.postgresql 5432; do echo "Waiting for database..."; sleep 1; done;']
        - name: wait-for-redis
          image: busybox:latest
          command: ['sh', '-c', 'until nc -vz redis-svc.redis 6379; do echo "Waiting for redis..."; sleep 1; done;']
        - name: wait-for-smart-contract-verifier
          image: busybox:latest
          command: ['sh', '-c', 'until nc -vz smart-contract-verifier-svc 8050; do echo "Waiting for smart-contract-verifier..."; sleep 1; done;']

      containers:
        - name: app-blockscout
          image: onthertech/tokamak.blockscout
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
              protocol: TCP
          command: ['/bin/sh','-c']
          args: ['bin/blockscout eval "Elixir.Explorer.ReleaseTasks.create_and_migrate()" && bin/blockscout start']
          envFrom:
            - configMapRef:
                name: blockscout
            - secretRef:
                name: secret
