{
 "title": "Application DashBoard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Healthy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "L2 Geth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"l2geth\"}",
     "legendFormat": "L2 Geth"
    }
   ]
  },
  {
   "title": "Batch Submitter",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"batch-submitter\"}",
     "legendFormat": "Batch Submitter"
    }
   ]
  },
  {
   "title": "Data Transport Layer",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"data-transport-layer\"}",
     "legendFormat": "Data Transport Layer"
    }
   ]
  },
  {
   "title": "L2 Geth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Block",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_head_block{job=~\"l2geth\"}"
    }
   ]
  },
  {
   "title": "Chain head",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "chain_head_receipt{job=~\"l2geth\"}",
     "legendFormat": "transaction"
    },
    {
     "expr": "chain_head_block{job=~\"l2geth\"}",
     "legendFormat": "block"
    }
   ]
  },
  {
   "title": "Transaction",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_head_receipt{job=~\"l2geth\"}"
    }
   ]
  },
  { "title": "Batch Submitter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Sequencer Balance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "batch_submitter_sequencer_balance_eth{job=\"batch-submitter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batch Submissions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 13 },
   "targets": [
    {
     "expr": "batch_submitter_sequencer_batches_submitted{job=\"batch-submitter\"}",
     "legendFormat": "sequencer"
    },
    {
     "expr": "batch_submitter_proposer_batches_submitted{job=\"batch-submitter\"}",
     "legendFormat": "proposer"
    }
   ]
  },
  {
   "title": "Batch Failed Submissions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 13 },
   "targets": [
    {
     "expr": "batch_submitter_sequencer_failed_submissions{job=\"batch-submitter\"}",
     "legendFormat": "sequencer"
    },
    {
     "expr": "batch_submitter_proposer_failed_submissions{job=\"batch-submitter\"}",
     "legendFormat": "proposer"
    }
   ]
  },
  {
   "title": "Proposer Balance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "batch_submitter_proposer_balance_eth{job=\"batch-submitter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Data Transport Layer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "L1 Synced Block",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "data_transport_layer_highest_synced_l1_block{job=\"data-transport-layer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Main Service Failures",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 20 },
   "targets": [
    {
     "expr": "data_transport_layer_main_service_failures{job=\"data-transport-layer\"}",
     "legendFormat": "count"
    }
   ]
  }
 ]
}