ws_method_whitelist = [
  "admin_addPeer",
  "admin_addTrustedPeer",
  "admin_datadir",
  "admin_exportChain",
  "admin_importChain",
  "admin_nodeInfo",
  "admin_peerEvents",
  "admin_peers",
  "admin_removePeer",
  "admin_removeTrustedPeer",
  "admin_startHTTP",
  "admin_startWS",
  "admin_stopHTTP",
  "admin_stopWS",

  "clique_getSnapshot",
  "clique_getSnapshotAtHash",
  "clique_getSigner",
  "clique_getSigners",
  "clique_getSignersAtHash",
  "clique_proposals",
  "clique_propose",
  "clique_discard",
  "clique_status",

  "debug_accountRange",
  "debug_backtraceAt",
  "debug_blockProfile",
  "debug_chaindbCompact",
  "debug_chaindbProperty",
  "debug_cpuProfile",
  "debug_dbAncient",
  "debug_dbAncients",
  "debug_dbGet",
  "debug_dumpBlock",
  "debug_freeOSMemory",
  "debug_freezeClient",
  "debug_gcStats",
  "debug_getAccessibleState",
  "debug_getBadBlocks",
  "debug_getRawBlock",
  "debug_getRawHeader",
  "debug_getRawTransaction",
  "debug_getModifiedAccountsByHash",
  "debug_getModifiedAccountsByNumber",
  "debug_getRawReceipts",
  "debug_goTrace",
  "debug_intermediateRoots",
  "debug_memStats",
  "debug_mutexProfile",
  "debug_preimage",
  "debug_printBlock",
  "debug_seedHash",
  "debug_setBlockProfileRate",
  "debug_setGCPercent",
  "debug_setHead",
  "debug_setMutexProfileFraction",
  "debug_setTrieFlushInterval",
  "debug_stacks",
  "debug_standardTraceBlockToFile",
  "debug_standardTraceBadBlockToFile",
  "debug_startCPUProfile",
  "debug_startGoTrace",
  "debug_stopCPUProfile",
  "debug_stopGoTrace",
  "debug_storageRangeAt",
  "debug_traceBadBlock",
  "debug_traceBlock",
  "debug_traceBlockByNumber",
  "debug_traceBlockByHash",
  "debug_traceBlockFromFile",
  "debug_traceCall",
  "debug_traceChain",
  "debug_traceTransaction",
  "debug_verbosity",
  "debug_vmodule",
  "debug_writeBlockProfile",
  "debug_writeMemProfile",
  "debug_writeMutexProfile",

  "web3_clientVersion",
  "web3_sha3",

  "net_version",
  "net_listening",
  "net_peerCount",

  "eth_protocolVersion",
  "eth_syncing",
  "eth_coinbase",
  "eth_chainId",
  "eth_mining",
  "eth_hashrate",
  "eth_gasPrice",
  "eth_accounts",
  "eth_blockNumber",
  "eth_getBalance",
  "eth_getStorageAt",
  "eth_getTransactionCount",
  "eth_getBlockTransactionCountByHash",
  "eth_getBlockTransactionCountByNumber",
  "eth_getUncleCountByBlockHash",
  "eth_getUncleCountByBlockNumber",
  "eth_getCode",
  "eth_sign",
  "eth_signTransaction",
  "eth_sendTransaction",
  "eth_sendRawTransaction",
  "eth_call",
  "eth_estimateGas",
  "eth_getBlockByHash",
  "eth_getBlockByNumber",
  "eth_getTransactionByHash",
  "eth_getTransactionByBlockHashAndIndex",
  "eth_getTransactionByBlockNumberAndIndex",
  "eth_getTransactionReceipt",
  "eth_getUncleByBlockHashAndIndex",
  "eth_getUncleByBlockNumberAndIndex",
  "eth_getCompilers",
  "eth_compileSolidity",
  "eth_compileLLL",
  "eth_compileSerpent",
  "eth_newFilter",
  "eth_newBlockFilter",
  "eth_newPendingTransactionFilter",
  "eth_uninstallFilter",
  "eth_getFilterChanges",
  "eth_getFilterLogs",
  "eth_getLogs",
  "eth_getWork",
  "eth_submitWork",
  "eth_submitHashrate",
  "eth_subscribe",
  "eth_unsubscribe",
  "eth_createAccessList",
  "eth_getHeaderByNumber",
  "eth_getHeaderByHash",

  "les_serverInfo",
  "les_clientInfo",
  "les_priorityClientInfo",
  "les_addBalance",
  "les_setClientParams",
  "les_setDefaultParams",
  "les_latestCheckpoint",
  "les_getCheckpoint",
  "les_getCheckpointContractAddress",

  "txpool_content",
  "txpool_contentFrom",
  "txpool_inspect",
  "txpool_status",

  "eth_getBlockRange",
  "rollup_getInfo",
  "rollup_gasPrices"
]

ws_backend_group = "l2geth"

[server]
rpc_host = "0.0.0.0"
rpc_port = 8080
ws_host = "0.0.0.0"
ws_port = 8085
max_body_size_bytes = 10485760
max_concurrent_rpcs = 10000
log_level = "info"
timeout_seconds = 300
# In worst case, all backend total tries * timeouts

[redis]
url = "redis://redis-svc.redis:6379/1"

[cache]
enabled = true
block_sync_rpc_url = "http://l2geth-0.l2geth-svc:8545"

[metrics]
enabled = true
host = "0.0.0.0"
port = 9761

[backend]
response_timeout_seconds = 5
max_response_size_bytes = 5242880
max_retries = 1
out_of_service_seconds = 0

[backends]
[backends.l2geth]
rpc_url = "http://l2geth-0.l2geth-svc:8545"
ws_url = "ws://l2geth-0.l2geth-svc:8546"
max_rps = 0
max_ws_conns = 0

[backends.l2geth-replica]
rpc_url = "http://l2geth-replica-0.l2geth-replica-svc:8545"
ws_url = "ws://l2geth-replica-0.l2geth-replica-svc:8546"
max_rps = 0
max_ws_conns = 0

[backend_groups]
[backend_groups.l2geth]
backends = ["l2geth"]

[backend_groups.l2geth-replica]
backends = ["l2geth-replica"]

[rpc_method_mappings]
admin_addPeer = "l2geth"
admin_addTrustedPeer = "l2geth"
admin_datadir = "l2geth"
admin_exportChain = "l2geth"
admin_importChain = "l2geth"
admin_nodeInfo = "l2geth"
admin_peerEvents = "l2geth"
admin_peers = "l2geth"
admin_removePeer = "l2geth"
admin_removeTrustedPeer = "l2geth"
admin_startHTTP = "l2geth"
admin_startWS = "l2geth"
admin_stopHTTP = "l2geth"
admin_stopWS = "l2geth"

clique_getSnapshot = "l2geth"
clique_getSnapshotAtHash = "l2geth"
clique_getSigner = "l2geth"
clique_getSigners = "l2geth"
clique_getSignersAtHash = "l2geth"
clique_proposals = "l2geth"
clique_propose = "l2geth"
clique_discard = "l2geth"
clique_status = "l2geth"

debug_accountRange = "l2geth"
debug_backtraceAt = "l2geth"
debug_blockProfile = "l2geth"
debug_chaindbCompact = "l2geth"
debug_chaindbProperty = "l2geth"
debug_cpuProfile = "l2geth"
debug_dbAncient = "l2geth"
debug_dbAncients = "l2geth"
debug_dbGet = "l2geth"
debug_dumpBlock = "l2geth"
debug_freeOSMemory = "l2geth"
debug_freezeClient = "l2geth"
debug_gcStats = "l2geth"
debug_getAccessibleState = "l2geth"
debug_getBadBlocks = "l2geth"
debug_getRawBlock = "l2geth"
debug_getRawHeader = "l2geth"
debug_getRawTransaction = "l2geth"
debug_getModifiedAccountsByHash = "l2geth"
debug_getModifiedAccountsByNumber = "l2geth"
debug_getRawReceipts = "l2geth"
debug_goTrace = "l2geth"
debug_intermediateRoots = "l2geth"
debug_memStats = "l2geth"
debug_mutexProfile = "l2geth"
debug_preimage = "l2geth"
debug_printBlock = "l2geth"
debug_seedHash = "l2geth"
debug_setBlockProfileRate = "l2geth"
debug_setGCPercent = "l2geth"
debug_setHead = "l2geth"
debug_setMutexProfileFraction = "l2geth"
debug_setTrieFlushInterval = "l2geth"
debug_stacks = "l2geth"
debug_standardTraceBlockToFile = "l2geth"
debug_standardTraceBadBlockToFile = "l2geth"
debug_startCPUProfile = "l2geth"
debug_startGoTrace = "l2geth"
debug_stopCPUProfile = "l2geth"
debug_stopGoTrace = "l2geth"
debug_storageRangeAt = "l2geth"
debug_traceBadBlock = "l2geth"
debug_traceBlock = "l2geth"
debug_traceBlockByNumber = "l2geth"
debug_traceBlockByHash = "l2geth"
debug_traceBlockFromFile = "l2geth"
debug_traceCall = "l2geth"
debug_traceChain = "l2geth"
debug_traceTransaction = "l2geth"
debug_verbosity = "l2geth"
debug_vmodule = "l2geth"
debug_writeBlockProfile = "l2geth"
debug_writeMemProfile = "l2geth"
debug_writeMutexProfile = "l2geth"

web3_clientVersion = "l2geth"
web3_sha3 = "l2geth"

net_version = "l2geth"
net_listening = "l2geth"
net_peerCount = "l2geth"

eth_protocolVersion = "l2geth"
eth_syncing = "l2geth"
eth_coinbase = "l2geth"
eth_chainId = "l2geth"
eth_mining = "l2geth"
eth_hashrate = "l2geth"
eth_gasPrice = "l2geth"
eth_accounts = "l2geth"
eth_blockNumber = "l2geth"
eth_getBalance = "l2geth"
eth_getStorageAt = "l2geth"
eth_getTransactionCount = "l2geth"
eth_getBlockTransactionCountByHash = "l2geth"
eth_getBlockTransactionCountByNumber = "l2geth"
eth_getUncleCountByBlockHash = "l2geth"
eth_getUncleCountByBlockNumber = "l2geth"
eth_getCode = "l2geth"
eth_sign = "l2geth"
eth_signTransaction = "l2geth"
eth_sendTransaction = "l2geth"
eth_sendRawTransaction = "l2geth"
eth_call = "l2geth"
eth_estimateGas = "l2geth"
eth_getBlockByHash = "l2geth"
eth_getBlockByNumber = "l2geth"
eth_getTransactionByHash = "l2geth"
eth_getTransactionByBlockHashAndIndex = "l2geth"
eth_getTransactionByBlockNumberAndIndex = "l2geth"
eth_getTransactionReceipt = "l2geth"
eth_getUncleByBlockHashAndIndex = "l2geth"
eth_getUncleByBlockNumberAndIndex = "l2geth"
eth_getCompilers = "l2geth"
eth_compileSolidity = "l2geth"
eth_compileLLL = "l2geth"
eth_compileSerpent = "l2geth"
eth_newFilter = "l2geth"
eth_newBlockFilter = "l2geth"
eth_newPendingTransactionFilter = "l2geth"
eth_uninstallFilter = "l2geth"
eth_getFilterChanges = "l2geth"
eth_getFilterLogs = "l2geth"
eth_getLogs = "l2geth"
eth_getWork = "l2geth"
eth_submitWork = "l2geth"
eth_submitHashrate = "l2geth"
eth_subscribe = "l2geth"
eth_unsubscribe = "l2geth"
eth_createAccessList = "l2geth"
eth_getHeaderByNumber = "l2geth"
eth_getHeaderByHash = "l2geth"

les_serverInfo = "l2geth"
les_clientInfo = "l2geth"
les_priorityClientInfo = "l2geth"
les_addBalance = "l2geth"
les_setClientParams = "l2geth"
les_setDefaultParams = "l2geth"
les_latestCheckpoint = "l2geth"
les_getCheckpoint = "l2geth"
les_getCheckpointContractAddress = "l2geth"

txpool_content = "l2geth"
txpool_contentFrom = "l2geth"
txpool_inspect = "l2geth"
txpool_status = "l2geth"

# l2geth rpc
eth_getBlockRange = "l2geth"
rollup_getInfo = "l2geth"
rollup_gasPrices = "l2geth"

[rate_limit]
enable_backend_rate_limiter = false

[sender_rate_limit]
enabled = false
