apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  template:
    spec:
      containers:
      - name: redis
        resources:
          requests:
            cpu: 0.5
            memory: 0.75Gi
        volumeMounts:
        - name: redis-volume
          mountPath: /data
          subPath: redis
      volumes:
      - name: redis-volume
        persistentVolumeClaim:
          claimName: redis-pvc
