---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-notif
spec:
  template:
    spec:
      containers:
        - name: app-notif
          envFrom:
            - configMapRef:
                name: notif-app-config
