apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: developer-role
rules:
  - apiGroups:
      - "*"
    resources:
      - "configmaps"
      - "endpoints"
      - "events"
      - "namespaces"
      - "nodes"
      - "persistentvolumes"
      - "persistentvolumeclaims"
      - "pods"
      - "pods/portforward"
      - "pods/proxy"
      - "pods/log"
      - "podtemplates"
      - "replicationcontrollers"
      - "resourcequotas"
      - "services"
      - "daemonsets"
      - "deployments"
      - "replicasets"
      - "statefulsets"
      - "cronjobs"
      - "jobs"
      - "alertmanagerconfigs"
      - "podmonitors"
      - "prometheuses"
      - "prometheusrules"
      - "servicemonitors"
      - "ingresses"
      - "networkpolicies"
    verbs:
      - "*"
