apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-blockscout

generatorOptions:
  disableNameSuffixHash: true

resources:
  - namespace.yaml
  - ingress.yaml
  - ../../../envs/mainnet
  - ../../../bases/blockscout
  - ../../../bases/smart-contract-verifier
  - ../../../bases/visualizer
  - ../../../bases/sig-provider

configMapGenerator:
  - literals:
      - APP_NAME=blockscout
      - CLUSTER_NAME=mainnet
      - ENV_NAME=aws
    name: app-blockscout-config

images:
  - name: tokamaknetwork/titan-explorer
    newTag: release-1.2.9

patches:
  - path: resource_override.yaml
