---
apiVersion: v1
kind: Service
metadata:
  name: proxyd-svc
spec:
  ports:
    - name: http
      port: 8545
      protocol: TCP
      targetPort: 8080
    - name: ws
      port: 8546
      protocol: TCP
      targetPort: 8085
    - name: metric
      port: 9761
      protocol: TCP
      targetPort: 9761
  selector:
    app: proxyd
