apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: common
    envs:
      - ./common.env
  - name: op-geth
    envs:
      - ./op-geth.env
  - name: op-node
    envs:
      - ./op-node.env
