apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tokamak-optimism-monitoring
spec:
  project: default
  sources:
    # kube-prometheus-stack
    - repoURL: 'https://prometheus-community.github.io/helm-charts'
      chart: kube-prometheus-stack
      targetRevision: '*-0'
      helm:
        valueFiles:
          - $repo/monitoring/metrics/override_values/aws/mainnet/alert-rules.yaml
          - $repo/monitoring/metrics/override_values/aws/mainnet/base.yaml
          - $repo/monitoring/metrics/override_values/aws/mainnet/resources.yaml
    # prometheus-blackbox-exporter
    - repoURL: 'https://prometheus-community.github.io/helm-charts'
      chart: prometheus-blackbox-exporter
      targetRevision: '*-0'
      helm:
        valueFiles:
          - $repo/monitoring/metrics/override_values/aws/mainnet/blackbox.yaml
    # grafana dashboards
    - repoURL: 'https://github.com/tokamak-network/tokamak-infra.git'
      path: monitoring/metrics/dashboards
      targetRevision: main
    # repoURL
    - repoURL: 'https://github.com/tokamak-network/tokamak-infra.git'
      targetRevision: main
      ref: repo

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
