---
# Source: elasticsearch/templates/service.yaml
kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: elastic-stack
  labels:
    app: "elasticsearch"
spec:
  type: ClusterIP
  selector:
    app: "elasticsearch"
  publishNotReadyAddresses: false
  ports:
  - name: http
    protocol: TCP
    port: 9200
  - name: transport
    protocol: TCP
    port: 9300