apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../config

resources:
  - ../../bases
  - ingress.yaml

patchesStrategicMerge:
  - resource_override.yaml
  - service_override.yaml
