apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-gateway
spec:
  template:
    spec:
      containers:
        - name: app-gateway
          resources:
            requests:
              cpu: 1
              memory: 1Gi
