apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tokamakoptimism-ext-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: tokamak-optimism-secretstore
    kind: SecretStore
  target:
    name: secret
    creationPolicy: Owner
  data:
  - secretKey: BATCH_SUBMITTER_SEQUENCER_PRIVATE_KEY
    remoteRef:
      key: titan-mainnet/secrets
      property: BATCH_SUBMITTER_SEQUENCER_PRIVATE_KEY
  - secretKey: BATCH_SUBMITTER_PROPOSER_PRIVATE_KEY
    remoteRef:
      key: titan-mainnet/secrets
      property: BATCH_SUBMITTER_PROPOSER_PRIVATE_KEY
  - secretKey: MESSAGE_RELAYER__L1_WALLET
    remoteRef:
      key: titan-mainnet/secrets
      property: MESSAGE_RELAYER__L1_WALLET
  - secretKey: GAS_PRICE_ORACLE_PRIVATE_KEY
    remoteRef:
      key: titan-mainnet/secrets
      property: GAS_PRICE_ORACLE_PRIVATE_KEY
