apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: titan

generatorOptions:
  disableNameSuffixHash: true

# - ../../../bases/gas-oracle
resources:
  - ../../../bases/data-transport-layer
  - ../../../bases/l2geth
  - ../../../bases/l2geth-replica
  - ../../../bases/tx-batch-submitter
  - ../../../bases/state-batch-submitter
  - ../../../bases/proxyd
  - ../../../bases/proxyd-l2geth
  - ingress.yaml
  - pv.yaml
  - pvc.yaml
  - secretstore.yaml
  - externalsecret.yaml
  - ../../../envs/mainnet
  - ../../../scripts

patches:
  - path: resource_override.yaml

configMapGenerator:
  - literals:
      - CLUSTER_NAME=mainnet
      - ENV_NAME=aws
    name: chain-config
images:
  - name: tokamaknetwork/titan-batch-submitter
    newTag: release-0.1.20
  - name: tokamaknetwork/titan-data-transport-layer
    newTag: release-0.1.20
  - name: tokamaknetwork/titan-gas-oracle
    newTag: release-0.1.20
  - name: tokamaknetwork/titan-l2geth
    newTag: release-0.1.20
  - name: tokamaknetwork/titan-message-relayer
    newTag: release-0.1.20
  - name: tokamaknetwork/titan-proxyd
    newTag: release-0.1.20
