apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
- ../../../bases/data-transport-layer
- ../../../bases/l2geth
- ../../../bases/l2geth-replica
- ../../../bases/batch-submitter
- ../../../bases/relayer
- ../../../bases/proxyd
# - ../../../bases/gas-oracle
- ../../../bases/roles
- ingress.yaml
- sc.yaml
- pv.yaml
- pvc.yaml
- aws-logging.yaml
- secretstore.yaml
- externalsecret.yaml
- ../../../envs/mainnet
- ../../../scripts

patchesStrategicMerge:
- resource_override.yaml

configMapGenerator:
- literals:
  - CLUSTER_NAME=mainnet
  - ENV_NAME=aws
  name: chain-config
