apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: tokamak-optimism-secretstore
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
      auth:
        jwt:
          serviceAccountRef:
            name: tokamak-optimism-deployment-sa
