apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../envs/hardhat
  - ../../scripts

resources:
  - ../../bases/data-transport-layer
  - ../../bases/l2geth
  - ../../bases/l1chain
  - ../../bases/deployer
  - ../../bases/batch-submitter
  - ../../bases/relayer
  - ./local-path-provisioner.yaml
  - ./pvc.yaml
