apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
spec:
  template:
    spec:
      containers:
      - name: postgresql
        resources:
          requests:
            cpu: 1
            memory: 1.75Gi
        volumeMounts:
        - name: postgresql-volume
          mountPath: /var/lib/postgresql/data
          subPath: postgresql
      volumes:
      - name: postgresql-volume
        persistentVolumeClaim:
          claimName: postgresql-pvc
