apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../config

resources:
  - ../../bases

configMapGenerator:
  - name: app-gateway-config
    behavior: merge
    literals:
      - APP_NAME=gateway
      - ENV_NAME=local
