apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: redis

generatorOptions:
  disableNameSuffixHash: true

resources:
- namespace.yaml
- pv.yaml
- pvc.yaml
- ../../../bases

patchesStrategicMerge:
- resource_override.yaml

configMapGenerator:
- literals:
  - APP_NAME=redis
  - CLUSTER_NAME=goerli-nightly
  - ENV_NAME=aws
  name: redis-config
