apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
spec:
  project: default
  source:
    repoURL: 'https://github.com/tokamak-network/tokamak-infra.git'
    path: ops/redis/kustomize/overlays/aws
    targetRevision: OR-1636-create-thanos-sepolia-nightly
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: redis
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
