---
apiVersion: v1
kind: Service
metadata:
  name: op-node-svc
spec:
  selector:
    app: op-node
  ports:
    - name: http
      port: 8545
      targetPort: 8545
    - name: metric
      port: 7300
      targetPort: 7300
    - name: pprof
      port: 6060
      targetPort: 6060
