---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: op-node
spec:
  selector:
    matchLabels:
      app: op-node
  replicas: 1
  serviceName: op-node-svc
  template:
    metadata:
      labels:
        app: op-node
    spec:
      terminationGracePeriodSeconds: 10
      restartPolicy: Always
      initContainers:
        - name: wait-for-l1
          image: nicolaka/netshoot
          command: ["bash", "-c", "/wait-scripts/wait-for-l1.sh"]
          volumeMounts:
            - name: wait-scripts
              mountPath: /wait-scripts
          envFrom:
            - configMapRef:
                name: common
        - name: wait-for-l2
          image: nicolaka/netshoot
          command: ["bash", "-c", "/wait-scripts/wait-for-l2.sh"]
          volumeMounts:
            - name: wait-scripts
              mountPath: /wait-scripts
          envFrom:
            - configMapRef:
                name: common
      containers:
        - name: op-node
          image: tokamaknetwork/thanos-op-node
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "/op-node-scripts/entrypoint-op-node.sh"]
          envFrom:
            - configMapRef:
                name: op-node
            - secretRef:
                name: secret
          ports:
            - containerPort: 8545
              protocol: TCP
            - containerPort: 7300
              protocol: TCP
            - containerPort: 6060
              protocol: TCP
          volumeMounts:
            - name: safedb-data
              mountPath: /safedb
              subPath: op-node
            - name: op-node-scripts
              mountPath: /op-node-scripts
            - name: op-geth-auth
              mountPath: /op-geth-auth

      volumes:
        - name: safedb-data
          persistentVolumeClaim:
            claimName: op-node-pvc
        - name: wait-scripts
          configMap:
            name: wait-scripts
            defaultMode: 0777
        - name: op-node-scripts
          configMap:
            name: op-node-scripts
            defaultMode: 0777
        - name: op-geth-auth
          configMap:
            name: op-geth-auth
            defaultMode: 0777
