---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ipfs-pvc
spec:
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  selector:
    matchLabels:
      app: ipfs
