apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: graph-node
    envs:
      - graph-node.env

secretGenerator:
  - name: secret
    envs:
      - ./secret.env