apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
- ../../../bases/elasticsearch
- ../../../bases/kibana
- pv.yaml
- ingress.yaml