apiVersion: apps/v1
kind: Deployment
metadata:
  name: op-proposer
spec:
  replicas: 1
  template:
    spec:
      terminationGracePeriodSeconds: 10
      restartPolicy: Always
      initContainers:
        - name: wait-for-rollup
          image: nicolaka/netshoot
          command: ['bash', '-c', '/wait-scripts/wait-for-rollup.sh']
          volumeMounts:
            - name: wait-scripts
              mountPath: /wait-scripts
          envFrom:
            - configMapRef:
                name: common
      containers:
        - name: proposer
          image: onthertech/titan-op-proposer
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8560
              protocol: TCP
          resources: {}
          envFrom:
            - configMapRef:
                name: op-proposer
      volumes:
        - name: wait-scripts
          configMap:
            name: wait-scripts
            defaultMode: 0777