apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-gateway

generatorOptions:
  disableNameSuffixHash: true

resources:
- ../../../bases
- namespace.yaml
- ingress.yaml

patchesStrategicMerge:
- resource_override.yaml

configMapGenerator:
- files:
  - config.json
  literals:
  - APP_NAME=gateway
  - CLUSTER_NAME=goerli
  - ENV_NAME=aws
  name: app-gateway-config
images:
- name: onthertech/tokamak.gateway
  newTag: release-0.2.55
