apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: titan2

generatorOptions:
  disableNameSuffixHash: true

resources:
- namespace.yaml
- ../../bases/op-geth
- ../../bases/op-node
- ../../bases/op-batcher
- ../../bases/op-proposer
- ../../bases/proxyd
- ../../envs/titan-sepolia-test
- ../../files
- pv.yaml
- pvc.yaml
- secretstore.yaml
- externalsecret.yaml
- ingress.yaml

patchesStrategicMerge:
- resource_override.yaml

images:
- name: onthertech/titan-op-batcher
  newTag: nightly-cefd4520
- name: onthertech/titan-op-geth
  newTag: nightly-ea65010a
- name: onthertech/titan-op-node
  newTag: nightly-cefd4520
- name: onthertech/titan-op-proposer
  newTag: nightly-cefd4520
- name: onthertech/titan-proxyd
  newTag: nightly-cefd4520
