apiVersion: v1
kind: Service
metadata:
  name: op-batcher-svc
spec:
  selector:
    app: op-batcher
  ports:
    - name: http
      port: 8548
      protocol: TCP
      targetPort: 8548
    - name: metric
      port: 7300
      targetPort: 7300
