ws_method_whitelist = [
  "eth_subscribe",
  "eth_call",
  "eth_chainId",
  "net_version",
]
ws_backend_group = "main"

[server]
rpc_host = "0.0.0.0"
rpc_port = 8080
ws_host = "0.0.0.0"
ws_port = 8085
max_body_size_bytes = 10485760
max_concurrent_rpcs = 10000
log_level = "warn"
timeout_seconds = 300
# In worst case, all backend total tries * timeouts

[redis]
url = "redis://redis-svc.redis:6379/0"

[cache]
enabled = true
block_sync_rpc_url = "https://goerli.rpc.tokamak.network"

[metrics]
enabled = true
host = "0.0.0.0"
port = 9761

[backend]
response_timeout_seconds = 30
max_response_size_bytes = 5242880
max_retries = 1
out_of_service_seconds = 20

[backends]
[backends.infura_steven1]
rpc_url = "https://goerli.infura.io/v3/98934cc6fa14459f8e5ee0cdfe1eed0a"
ws_url = "wss://goerli.infura.io/ws/v3/98934cc6fa14459f8e5ee0cdfe1eed0a"
max_rps = 1000
max_ws_conns = 0

[backends.infura_steven2]
rpc_url = "https://goerli.infura.io/v3/274dc9c47885483ca708968ee0e75d06"
ws_url = "wss://goerli.infura.io/ws/v3/274dc9c47885483ca708968ee0e75d06"
max_rps = 1000
max_ws_conns = 0

[backends.infura_theo1]
rpc_url = "https://goerli.infura.io/v3/053e5d95616744d4b30a80fb885bacb8"
ws_url = "wss://goerli.infura.io/ws/v3/053e5d95616744d4b30a80fb885bacb8"
max_rps = 1000
max_ws_conns = 0

[backends.infura_theo2]
rpc_url = "https://goerli.infura.io/v3/adbdb3ac93674147934afa48bdccacef"
ws_url = "wss://goerli.infura.io/ws/v3/adbdb3ac93674147934afa48bdccacef"
max_rps = 1000
max_ws_conns = 0

[backends.office]
rpc_url = "https://goerli.rpc.tokamak.network"
ws_url = "ws://goerli.rpc.tokamak.network:8546"
max_rps = 1000
max_ws_conns = 0

[backend_groups]
[backend_groups.main]
backends = [
  "office",
  "infura_steven1",
  "infura_steven2",
  "infura_theo1",
  "infura_theo2",
]

[backend_groups.heavy_request]
backends = ["infura_theo2", "infura_theo1", "infura_steven2", "infura_steven1"]

[rpc_method_mappings]
net_version = "main"
web3_clientVersion = "main"
eth_call = "main"
eth_chainId = "main"
eth_blockNumber = "main"
eth_estimateGas = "main"
eth_feeHistory = "main"
eth_getBalance = "main"
eth_getBlockByHash = "main"
eth_getBlockByNumber = "main"
eth_getCode = "main"
eth_getLogs = "heavy_request"
eth_gasPrice = "main"
eth_getTransactionByHash = "main"
eth_getTransactionCount = "main"
eth_getTransactionReceipt = "main"
eth_sendRawTransaction = "main"
eth_maxPriorityFeePerGas = "main"

[rate_limit]
enable_backend_rate_limiter = true
