ws_method_whitelist = [
  "eth_subscribe",
  "eth_call",
  "eth_chainId",
  "net_version"
]
ws_backend_group = "main"

[server]
rpc_host = "0.0.0.0"
rpc_port = 8080
ws_host = "0.0.0.0"
ws_port = 8085
max_body_size_bytes = 10485760
max_concurrent_rpcs = 10000
log_level = "warn"
timeout_seconds = 30

[redis]
url = "redis://redis-svc.redis:6379"

[cache]
enabled = true
block_sync_rpc_url = "https://goerli.rpc.tokamak.network"

[metrics]
enabled = true
host = "0.0.0.0"
port = 9761

[backend]
response_timeout_seconds = 30
max_response_size_bytes = 5242880
max_retries = 2
out_of_service_seconds = 600

[backends]
[backends.infura_harry1]
rpc_url = "https://goerli.infura.io/v3/186eabd9aafb4012a6916de780348a4e"
ws_url = "wss://goerli.infura.io/ws/v3/186eabd9aafb4012a6916de780348a4e"
max_rps = 1000
max_ws_conns = 1

[backends.infura_harry2]
rpc_url = "https://goerli.infura.io/v3/8485ff6b2da443c28c37faae6d42a06b"
ws_url = "wss://goerli.infura.io/ws/v3/8485ff6b2da443c28c37faae6d42a06b"
max_rps = 1000
max_ws_conns = 1

[backends.infura_harry3]
rpc_url = "https://goerli.infura.io/v3/a07126fa968a4f918e275164f25a6862"
ws_url = "wss://goerli.infura.io/ws/v3/a07126fa968a4f918e275164f25a6862"
max_rps = 1000
max_ws_conns = 1

[backends.alchemy_harry1]
rpc_url = "https://eth-goerli.g.alchemy.com/v2/z6Qfnx7YwupKVilzZJTHfgc8nVOynOr1"
ws_url = "wss://eth-goerli.g.alchemy.com/v2/z6Qfnx7YwupKVilzZJTHfgc8nVOynOr1"
max_rps = 1000
max_ws_conns = 1

[backends.office]
rpc_url = "https://goerli.rpc.tokamak.network"
ws_url = "ws://goerli.rpc.tokamak.network:8546"
max_rps = 1000
max_ws_conns = 1

[backend_groups]
[backend_groups.main]
backends = ["office", "infura_harry1", "infura_harry2", "infura_harry3", "alchemy_harry1"]

[backend_groups.alchemy]
backends = ["alchemy_harry1"]

[backend_groups.infura]
backends = ["infura_harry1", "infura_harry2", "infura_harry3"]

[rpc_method_mappings]
net_version = "main"
web3_clientVersion = "main"
eth_call = "main"
eth_chainId = "main"
eth_blockNumber = "main"
eth_estimateGas = "main"
eth_feeHistory = "main"
eth_getBalance = "main"
eth_getBlockByHash = "main"
eth_getBlockByNumber = "main"
eth_getCode = "main"
eth_getLogs = "main"
eth_gasPrice = "main"
eth_getTransactionByHash = "main"
eth_getTransactionCount = "main"
eth_getTransactionReceipt = "main"
eth_sendRawTransaction = "main"
eth_maxPriorityFeePerGas = "main"

[rate_limit]
enable_backend_rate_limiter = false

[sender_rate_limit]
enabled = false
