apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: thanos-app-notif
generatorOptions:
  disableNameSuffixHash: true

resources:
- namespace.yml
- ../../../bases
- ../../../envs/thanos-sepolia

patches:
- path: resource_override.yml

images:
- name: tokamaknetwork/thanos-event-listener
  newTag: nightly-72da7d0f
