apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-app-notif
spec:
  template:
    spec:
      containers:
        - name: thanos-app-notif
          envFrom:
            - configMapRef:
                name: thanos-notif-app-config
