apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blockscout
spec:
  project: default
  source:
    repoURL: 'https://github.com/tokamak-network/tokamak-infra.git'
    path: apps/blockscout/kustomize/overlays/aws/goerli
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: app-blockscout
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
