apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: graph-node
spec:
  project: default
  source:
    repoURL: 'https://github.com/tokamak-network/tokamak-infra.git'
    path: ops/graph-node/kustomize/overlays/aws/goerli
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: thegraph
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
