apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
  - ../../../bases

configMapGenerator:
  - name: app-gateway-config
    literals:
      - APP_NAME=gateway
      - CLUSTER_NAME=hardhat
      - ENV_NAME=local
    files:
      - config.json
