apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
spec:
  project: default
  sources:
    # kube-prometheus-stack
    - repoURL: 'https://prometheus-community.github.io/helm-charts'
      chart: kube-prometheus-stack
      targetRevision: '*-0'
      helm:
        valueFiles:
          - $repo/monitoring/metrics/override_values/aws/thanos-sepolia/config.yaml
          - $repo/monitoring/metrics/override_values/aws/thanos-sepolia/prometheus.yaml
          - $repo/monitoring/metrics/override_values/aws/thanos-sepolia/alerts/alerts-common.yaml
          - $repo/monitoring/metrics/override_values/aws/thanos-sepolia/alerts/alerts-op-node.yaml
          - $repo/monitoring/metrics/override_values/aws/thanos-sepolia/alerts/alerts-op-batcher.yaml
          - $repo/monitoring/metrics/override_values/aws/thanos-sepolia/alerts/alerts-op-proposer.yaml
          - $repo/monitoring/metrics/override_values/aws/thanos-sepolia/alerts/alerts-graph-node.yaml
    # prometheus-blackbox-exporter
    - repoURL: 'https://prometheus-community.github.io/helm-charts'
      chart: prometheus-blackbox-exporter
      targetRevision: '*-0'
      helm:
        valueFiles:
          - $repo/monitoring/metrics/override_values/aws/thanos-sepolia/blackbox.yaml
    # grafana dashboards
    # - repoURL: 'https://github.com/tokamak-network/tokamak-infra.git'
    #   path: monitoring/metrics/dashboards
    #   targetRevision: main
    # repository to override
    - repoURL: 'https://github.com/tokamak-network/tokamak-infra.git'
      targetRevision: main
      ref: repo

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
