apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-gateway
spec:
  template:
    spec:
      containers:
        - name: app-gateway
          image: onthertech/tokamak.gateway:nightly
          imagePullPolicy: Always
