apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-notif
generatorOptions:
  disableNameSuffixHash: true

resources:
- namespace.yaml
- ../../../bases
- ../../../envs/mainnet

patchesStrategicMerge:
- resource_override.yaml
images:
- name: onthertech/titan-events-listener
  newTag: release-0.1.3
