apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-notif
generatorOptions:
  disableNameSuffixHash: true

resources:
  - namespace.yaml
  - ../../../bases
  - ../../../envs/mainnet

patches:
  - path: resource_override.yaml

images:
  - name: tokamaknetwork/titan-events-listener
    newTag: release-0.1.3
