---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-notif
spec:
  template:
    spec:
      containers:
        - name: app-notif
          image: tokamaknetwork/titan-events-listener:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: notif-app-config
