ws_method_whitelist = [
  "eth_subscribe",
  "eth_call",
  "eth_chainId",
  "net_version"
]
ws_backend_group = "main"

[server]
rpc_host = "0.0.0.0"
rpc_port = 8080
ws_host = "0.0.0.0"
ws_port = 8085
max_body_size_bytes = 10485760
max_concurrent_rpcs = 1000

[redis]
url = "redis://redis-svc.redis:6379"

[cache]
enabled = true
block_sync_rpc_url = "http://l1chain-svc:8545"

[metrics]
enabled = true
host = "0.0.0.0"
port = 9761

[backend]
response_timeout_seconds = 10
max_response_size_bytes = 5242880
max_retries = 3
out_of_service_seconds = 600

[backends]
[backends.hardhat]
rpc_url = "http://l1chain-svc:8545"
ws_url = "http://l1chain-svc:8546"
max_rps = 200
max_ws_conns = 1

[backend_groups]
[backend_groups.main]
backends = ["hardhat"]

[rpc_method_mappings]
net_version = "main"
web3_clientVersion = "main"
eth_call = "main"
eth_chainId = "main"
eth_blockNumber = "main"
eth_estimateGas = "main"
eth_feeHistory = "main"
eth_getBalance = "main"
eth_getBlockByHash = "main"
eth_getBlockByNumber = "main"
eth_getCode = "main"
eth_getLogs = "main"
eth_gasPrice = "main"
eth_getTransactionByHash = "main"
eth_getTransactionCount = "main"
eth_getTransactionReceipt = "main"
eth_sendRawTransaction = "main"
eth_maxPriorityFeePerGas = "main"

hardhat_setBalance = "main"

[rate_limit]
enable_backend_rate_limiter = false

[sender_rate_limit]
enabled = false
