apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  template:
    spec:
      terminationGracePeriodSeconds: 10
      restartPolicy: Always
      containers:
      - name: redis
        image: redis:alpine
        command: ['redis-server', '/redis-conf/redis.conf']
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
          protocol: TCP
        resources:
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - mountPath: /redis-conf
          name: redis-volume-config
      volumes:
      - name: redis-volume-config
        configMap:
          name: redis-service-config
          items:
          - key: redis-config-params
            path: redis.conf
