apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - redis-service-config.yaml
labels:
  - includeSelectors: true
    pairs:
      app: redis
