---
apiVersion: v1
kind: Service
metadata:
  name: graph-node-svc
spec:
  selector:
    app: graph-node
  ports:
    - name: http
      port: 8000
      targetPort: 8000
    - name: http
      port: 8001
      targetPort: 8001
    - name: http
      port: 8020
      targetPort: 8020
    - name: http
      port: 8030
      targetPort: 8030
    - name: http
      port: 8040
      targetPort: 8040
